<?php

namespace ShiftGearmanMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121102125815 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE shiftgearman_scheduler (id VARCHAR(250) NOT NULL, clientName VARCHAR(50) NOT NULL, runInBackground TINYINT(1) NOT NULL, priority VARCHAR(15) NOT NULL, jobName VARCHAR(250) NOT NULL, workload LONGTEXT DEFAULT NULL, start DATETIME DEFAULT NULL, repeatTimes INT NOT NULL, repeatInterval VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE shiftgearman_scheduler");
    }
}
